version: '2'
services:
  apt-proxy:
          #restart: always
    image: apt-proxy    
    ports:
      - "3142:3142/tcp"
    volumes:
      - ./acng.conf:/etc/apt-cacher-ng/acng.conf:ro
      - /var/log/apt-cacher-ng/:/var/log/apt-cacher-ng/:rw
      - /var/cache/apt-cacher-ng/:/var/cache/apt-cacher-ng/:rw
